feat: Staking V3
AstarNetwork/dapps-staking-indexer-v3 pull request #8
Opened 2023-12-08 01:08 UTC by gluneau

2023-12-12 14:24 UTC, bobo-k2 requested changes

2023-12-19 18:30 UTC, gluneau commented on src/processor.ts
> +    .setBlockRange({from: 1}) // .setBlockRange({from: 4_342_300})
Revert before merge

2023-12-19 18:31 UTC, gluneau commented on typegen.json
> +  "specVersionsProd": "https://v2.archive.subsquid.io/metadata/astar",
Revert before merge

2023-12-19 22:06 UTC, gluneau commented on src/main.ts
> +        default:
Thanks, it's now handled.

2023-12-20 15:08 UTC, bobo-k2 requested changes

2023-12-21 16:07 UTC, gluneau commented on src/main.ts
> +    assert(
blocks will always have a timestamp, it's the data type that can be undefined

2024-02-08 17:12 UTC, merged